name: JSON Linting
on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths:
      - "Gruntfile.coffee"
      - "**/*.json"
      - "**/*.json-ld"
      - ".github/workflows/lint-json.yml"

  pull_request:
    paths:
      - "Gruntfile.coffee"
      - "**/*.json"
      - "**/*.json-ld"
      - ".github/workflows/lint-json.yml"

jobs:
  lint-js:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          cache: npm

      - name: Install Grunt
        run: npm i -g grunt-cli --force

      - name: Install npm dependencies
        run: npm ci --ignore-scripts

      - name: JSONLint
        run: grunt jsonlint
